name: Build and Deploy

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            PUBLIC_URL: https://mizunashi-mana.github.io/react18-legacy-render-try/

        steps:
            -   uses: actions/checkout@v4

            -   name: Install npm dependencies
                run: npm ci

            -   name: Build
                run: npm run build

            -   name: Upload Pages artifacts
                uses: actions/upload-pages-artifact@v3
                with:
                    path: build/

    deploy:
        needs: build
        if: ${{ github.ref_name == 'main' }}

        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
